# -*- coding: utf-8 -*-
"""DigitClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebook#fileId=1GW2FPiTIepGEMum7EXwgDglbYo8oD9Tv
"""

from sklearn import datasets

iris = datasets.load_iris()

digits = datasets.load_digits()

print(digits.data)

print(digits.target)

digits.images[0]

from sklearn import svm

clf = svm.SVC(gamma=.001, C=100.)

clf.fit(digits.data[:-1], digits.target[:-1])

clf.predict(digits.data[-1:])

clf.predict(digits.data[-3:])

clf.predict(digits.data[:10])
